package biodiv.user;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
* Role generated by hbm2java
*/
@Entity
@Table(name = "role", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "authority"))
public class Role implements java.io.Serializable {

	private long id;
	private String authority;

	public Role() {
	}

	public Role(long id, String authority) {
		this.id = id;
		this.authority = authority;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "authority", unique = true, nullable = false)
	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

	@Override
	public String toString() {
		return "Role [id=" + id + ", authority=" + authority + "]";
	}

}
