package biodiv.scheduler;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import biodiv.user.User;

/**
 * DownloadLog generated by hbm2java
 */
@Entity
@Table(name = "download_log", schema = "public")
public class DownloadLog implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public enum DownloadType {
		CSV("CSV"), KML("KML"), PDF("PDF"), ZIP("ZIP"), TAR("TAR"), DWCA("DWCA");
		private String value;

		DownloadType(String value) {
			this.value = value;
		}

		String value() {
			return this.value;
		}
	}

	public enum SourceType {
		Observations("Observations");
		private String value;

		SourceType(String value) {
			this.value = value;
		}

		String value() {
			return this.value;
		}
	}

	private long id;
	private long version;
	private User user;
	private Date createdOn;
	private String filePath;
	private String filterUrl;
	private String notes;
	private String paramsMapAsText;
	private SchedulerStatus status;
	private DownloadType type;
	private SourceType sourceType;
	private long offsetParam;

	public DownloadLog() {
	}

	public DownloadLog(User user, String filterUrl, String notes, SchedulerStatus status, DownloadType type,
			SourceType sourceType, long offsetParam) {
		this.user = user;
		this.createdOn = new Date();
		this.filterUrl = filterUrl;
		this.notes = notes;
		this.status = status;
		this.type = type;
		this.sourceType = sourceType;
		this.offsetParam = offsetParam;
	}

	public DownloadLog(User user, String filePath, String filterUrl, String notes, String paramsMapAsText,
			SchedulerStatus status, DownloadType type, SourceType sourceType, long offsetParam) {
		this.user = user;
		this.createdOn = new Date();
		this.filePath = filePath;
		this.filterUrl = filterUrl;
		this.notes = notes;
		this.paramsMapAsText = paramsMapAsText;
		this.status = status;
		this.type = type;
		this.sourceType = sourceType;
		this.offsetParam = offsetParam;
	}

	@Id
	@GenericGenerator(name = "hibernate_generator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = {
			@Parameter(name = "sequence_name", value = "hibernate_sequence"),
			@Parameter(name = "increment_size", value = "1"), @Parameter(name = "optimizer", value = "hilo") })
	@GeneratedValue(generator = "hibernate_generator")
	@Column(name = "id", unique = true, updatable = false, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "author_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", nullable = false, length = 29)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "file_path")
	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	@Column(name = "filter_url", nullable = false)
	public String getFilterUrl() {
		return this.filterUrl;
	}

	public void setFilterUrl(String filterUrl) {
		this.filterUrl = filterUrl;
	}

	@Column(name = "notes")
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "params_map_as_text")
	public String getParamsMapAsText() {
		return this.paramsMapAsText;
	}

	public void setParamsMapAsText(String paramsMapAsText) {
		this.paramsMapAsText = paramsMapAsText;
	}

	@Column(name = "status", nullable = false)
	@Enumerated(EnumType.STRING)
	public SchedulerStatus getStatus() {
		return this.status;
	}

	public void setStatus(SchedulerStatus status) {
		this.status = status;
	}

	@Column(name = "type", nullable = false)
	@Enumerated(EnumType.STRING)
	public DownloadType getType() {
		return this.type;
	}

	public void setType(DownloadType type) {
		this.type = type;
	}

	@Column(name = "source_type")
	@Enumerated(EnumType.STRING)
	public SourceType getSourceType() {
		return this.sourceType;
	}

	public void setSourceType(SourceType sourceType) {
		this.sourceType = sourceType;
	}

	@Column(name = "offset_param", nullable = false)
	public long getOffsetParam() {
		return this.offsetParam;
	}

	public void setOffsetParam(long offsetParam) {
		this.offsetParam = offsetParam;
	}

}
