package biodiv.taxon.datamodel.dao;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * AcceptedSynonym generated by hbm2java
 */
@Entity
@Table(name = "accepted_synonym", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "synonym_id",
		"accepted_id" }))
public class AcceptedSynonyms implements java.io.Serializable {

	private long id;
	private long version;
	private long acceptedId;
	private long synonymId;

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "accepted_id", nullable = false)
	public long getAcceptedId() {
		return acceptedId;
	}

	public void setAcceptedId(long acceptedId) {
		this.acceptedId = acceptedId;
	}

	@Column(name = "synonym_id", nullable = false)
	public long getSynonymId() {
		return synonymId;
	}

	public void setSynonymId(long synonymId) {
		this.synonymId = synonymId;
	}

}
