package biodiv.taxon.datamodel.dao;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Classification generated by hbm2java
 */
@Entity
@Table(name = "classification", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
@Cache(region="species.Classification",usage = CacheConcurrencyStrategy.READ_ONLY,include="non-lazy")

public class Classification implements java.io.Serializable {
	private long id;
	private long version;
	//private Language language;
	private String name;
	private String citation;

	// private Set<TaxonomyRegistry> taxonomyRegistries = new HashSet(0);
	public Classification() {
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "language_id", nullable = false)
//	public Language getLanguage() {
//		return this.language;
//	}
//
//	public void setLanguage(Language language) {
//		this.language = language;
//	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "citation")
	public String getCitation() {
		return this.citation;
	}

	public void setCitation(String citation) {
		this.citation = citation;
	}
	/*
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy = "classification") public
	 * Set getTaxonomyRegistries() { return this.taxonomyRegistries; }
	 * 
	 * public void setTaxonomyRegistries(Set taxonomyRegistries) {
	 * this.taxonomyRegistries = taxonomyRegistries; }
	 */
}
