package biodiv.customField;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import biodiv.observation.Observation;

/**
 * CustomFieldsGroup18 generated by hbm2java
 */
@Entity
@Table(name = "custom_fields_group_18", schema = "public")
public class CustomFieldsGroup18 implements java.io.Serializable {

	private CustomFieldsGroup18Id id;
	private Observation observation;
	
	
	public CustomFieldsGroup18() {
	}

	public CustomFieldsGroup18(CustomFieldsGroup18Id id, Observation observation) {
		this.id = id;
		this.observation = observation;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "observationId", column = @Column(name = "observation_id", nullable = false)),
			@AttributeOverride(name = "cf5", column = @Column(name = "cf_5")),
			@AttributeOverride(name = "cf6", column = @Column(name = "cf_6")) })
	public CustomFieldsGroup18Id getId() {
		return this.id;
	}

	public void setId(CustomFieldsGroup18Id id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "observation_id", nullable = false, insertable = false, updatable = false)
	public Observation getObservation() {
		return this.observation;
	}

	public void setObservation(Observation observation) {
		this.observation = observation;
	}

}